#!/bin/sh
# Copyright (C) 2011 OpenWrt.org
# Copyright (C) 2015 Lantiq Beteiligungs-GmbH Co. KG

. /lib/falcon.sh

# uci has errors if the file does not exist:
touch /etc/config/goi_config

setup_single_ended_measurement() {
	uci batch <<EOF
	set goi_config.measurement.Tbosa_source=1
	set goi_config.measurement.V0K_Tref=1255
	set goi_config.measurement.Tscal_ref=0.468
EOF
}

setup_polarity_mod() {
	uci set goi_config.global.Polarity_Mod=0
}

# detect boards and do some default settings
case $(falcon_board_name) in
easy88384*|easy88388*)
	setup_single_ended_measurement
	setup_polarity_mod
	uci set goi_config.bosa.PICtrl=0x4029
	;;
*)
	return 0
	;;
esac

uci commit goi_config
