#!/bin/sh /etc/rc.common

START=97

start() {
	echo "0" > /proc/sys/net/ipv4/ip_forward
	while true
 	do
    	procid=`pgrep omcid`
    	if [ -z $procid ]; then
			reboot
    	fi
   	    sleep 5
 	done &
}

